### ISSUE TITLE
TypeError: SCSocket.prototype.stringify is not a function

### ISSUE THREAD

**Issue by imeay** [SocketCluster/socketcluster-server#11]
sc-broker-cluster depend on this module,but you had remove the stringify func. This modification leads to the error. #TypeError: SCSocket.prototype.stringify is not a function#

**Comment by f5io** [comment]
Relates to this [issue](https://github.com/SocketCluster/sc-broker-cluster/issues/1) on `sc-broker-cluster`. You can resolve this by hardening the dependency on `socketcluster-server` to 5.1.1 in your project as a quick fix.

**Comment by jondubois** [comment]
That's been fixed ages ago now thanks for reporting.
