### ISSUE TITLE
Include ws and uws as peer dependencies?

### ISSUE THREAD

**Issue by rockmacaca** [SocketCluster/socketcluster-server#16]
`uws` just got updated to 0.13 that has some important fixes for Windows and other performance-related changes. However socketcluster-server will only look at its locally installed version when resolving the `wsEngine` option passed in.

I feel like I should be able to have more control over this rather than waiting for this module to update with the bumped versions of these dependencies.

**Comment by jondubois** [comment]
@rockmacaca If you want to use a custom WebSockets engine or a uws version that is newer than is supported in SC, you can run add an entry for the latest uws in your main package.json: `"uws": "0.13.0",` then you `npm install uws@0.13.0` after that you will need to point to that exact top-level uws module by changing the `wsEngine` in server.js to:

`wsEngine: __dirname + '/node_modules/uws',`

SC will upgrade to `uws` 0.13.0 soon though so this it only for a little while.

**Comment by rockmacaca** [comment]
Ok. I also found that doing `require.resolve('uws')` works well. I suppose I'll close this since `require.resolve` basically solves my issue.
