### ISSUE TITLE
include websocket compression

### ISSUE THREAD

**Issue by mattkrick** [SocketCluster/socketcluster-server#2]
not immediately necessary, but WS compression has become pretty well established. might be worthwhile to add it. Might be able to borrow from https://github.com/faye/permessage-deflate-node

**Comment by toredash** [comment]
Can be closed, supported via:
>   // perMessageDeflate compression. Note that if you set it to true, you
>   // should also set it to true when instantiating the client socket.
>   perMessageDeflate: false,

https://socketcluster.io/#!/docs/api-socketcluster
