### ISSUE TITLE
SCServerSocket.kickOut doesn't modify `channelSubscriptions`

### ISSUE THREAD

**Issue by Aareksio** [SocketCluster/socketcluster-server#29]
https://github.com/SocketCluster/socketcluster-server/blob/master/scserversocket.js#L498

`SCServerSocket.kickOut` doesn't modify `channelSubscriptions` list making calling `SCServerSocket.subscriptions` return a list including channels the client is no longer subscribed to.

Moreover, it doesn't affect `SCServerSocket.channelSubscriptionsCount`, which may eventually lead to exceeding `SCServer.socketChannelLimit`.

**Comment by jondubois** [comment]
@Aareksio Thanks for raising this issue. It's been fixed in `v14.2.1`.
