### ISSUE TITLE
how to emit back to client?

### ISSUE THREAD

**Issue by xeroxstar** [SocketCluster/socketcluster-server#42]
Hey,
How do i send data back to the client? With socket.io i used to use emit method but it's seems it wont work with SC.. 

Here is the example:
**server.js**
```
    const socketClusterServer = require('socketcluster-server');
    const agServer = socketClusterServer.attach(server, options);
    
    (async () => {
        for await (let { socket } of agServer.listener('connection')) {
            socket.send('connected',true);//won't work
            socket.transmit('connected',true);//won't work
            socket.emit('connected',true);  //won't work
        }
    })();
```
**client.js**
```
let socket = require('socketcluster-client').create({
    hostname: 'localhost',
    port: 4000
});

(async () => {
    for await (let data of socket.receiver('connected')) {
        console.log(data)
    }
});
```

**Comment by jondubois** [comment]
@xeroxstar It has been renamed from `emit` to `transmit`. See https://socketcluster.io/docs/basic-usage/#client-transmit-messages-through-a-socket

This was done to avoid mistaking it for the `emit` method of `EventEmitter`.

**Comment by xeroxstar** [comment]
> @xeroxstar It has been renamed from `emit` to `transmit`. See https://socketcluster.io/docs/basic-usage/#client-transmit-messages-through-a-socket
> 
> This was done to avoid mistaking it for the `emit` method of `EventEmitter`.

So how i transmit back to the client? socket.transmit wont send back the data to the browser.

**Comment by jondubois** [comment]
@xeroxstar In `client.js`, the `async` block was declared but not invoked as an IIFE.

```
(async () => {
    for await (let data of socket.receiver('connected')) {
        console.log(data)
    }
});
```

should be

```
(async () => {
    for await (let data of socket.receiver('connected')) {
        console.log(data)
    }
})();
```

**Comment by jondubois** [comment]
Actually this is a common mistake (I've also done it a few times before). Maybe I will mention in the docs to be careful about this.

**Comment by jondubois** [comment]
Declaring IIFEs should get easier when `async do` becomes supported: https://github.com/tc39/proposal-do-expressions/issues/4

**Comment by xeroxstar** [comment]
It's so embarrassing, sorry for that.... you right, i did not invoke the method!!!

**Comment by jondubois** [comment]
No worries, it's easy to overlook. Happened to me as well in the past. That's why I'm looking forward to `async do` syntax.
