### ISSUE TITLE
TypeError: agServer.listener is not a function

### ISSUE THREAD

**Issue by xeroxstar** [SocketCluster/socketcluster-server#45]
Hello,
I am running this example : 
```
(async () => {
    const http = require('http');
    const socketClusterServer = require('socketcluster-server');

    let httpServer = http.createServer();
    let agServer = socketClusterServer.attach(httpServer);

    await (async () => {
        // Handle new inbound sockets.
        for await (let {socket} of agServer.listener('connection')) {

            await (async () => {
                // Set up a loop to handle and respond to RPCs for a procedure.
                for await (let req of socket.procedure('customProc')) {
                    if (req.data.bad) {
                        let error = new Error('Server failed to execute the procedure');
                        error.name = 'BadCustomError';
                        req.error(error);
                    } else {
                        req.end('Success');
                    }
                }
            })();

            await (async () => {
                // Set up a loop to handle remote transmitted events.
                for await (let data of socket.receiver('customRemoteEvent')) {
                    // ...
                }
            })();

        }
    })();

    httpServer.listen(8000);
})();
```
and I am getting an error:
`(node:4756) UnhandledPromiseRejectionWarning: TypeError: agServer.listener is not a function`

**"socketcluster-server": "^14.7.2"
node : v12.13.0**

**Comment by xeroxstar** [comment]
Sorry, wrong version. I installed **16.0.2** and it works again. 

_In WebStorm, after you done typing a module name in `package.json`,  the popup comes up with latest version for a current package and somehow 14.7.2 its the latest version for `socketcluster-server` in the list._
![image](https://user-images.githubusercontent.com/6754584/127500985-f21981ae-7502-4c62-8208-0c7b0f119009.png)

**Comment by jondubois** [comment]
@xeroxstar Ah yep that was the wrong version. For some reason, it shows 14.7.2 as the latest version on npm. I tried publishing a couple of new versions on top (now `16.0.4`) but they don't show up on the npm website for some reason. I will contact them to let them know about the issue.
